global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'techcare-dashboard'
    static_configs:
      - targets: ['dashboard:3000']
    metrics_path: '/api/metrics'

  - job_name: 'techcare-automator'
    static_configs:
      - targets: ['automator:9090']
    metrics_path: '/metrics'

  - job_name: 'techcare-scheduler'
    static_configs:
      - targets: ['scheduler:9090']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
